### ISSUE TITLE
why is every component surrounded with curly brackets

### ISSUE THREAD

**Issue by Sara-Samer** [abdoafage/Udemy-React-Clone-2#1]
https://github.com/abdoafage/Udemy-React-Clone-2/blob/800808d4938710631bfc09ce1a011cf83fcb637c/src/component/SingleCoursePage/PageComponent.js#L17-L28

**Comment by abdoafage** [comment]
I fixed this b0619cd5cd1500c28c8d0e461e524973061352cd
